# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-18 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nojapan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
