# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-19 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nojapan', '0002_category_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ManyToManyField(to='nojapan.category'),
        ),
    ]
