# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-24 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nojapan', '0006_auto_20190719_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='nojapan.category'),
        ),
    ]
