# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-29 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nojapan', '0008_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='produce',
        ),
        migrations.RemoveField(
            model_name='company',
            name='replace',
        ),
        migrations.AddField(
            model_name='company',
            name='replace',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
