# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Matchs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('result', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemberAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemberHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('yellow', models.IntegerField()),
                ('red', models.IntegerField()),
                ('shoot', models.IntegerField()),
                ('passs', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Matchs')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=200)),
                ('myteam', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('privilege', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Nations')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('mmr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Nations')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Roles')),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Users'),
        ),
        migrations.AddField(
            model_name='teams',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Leagues'),
        ),
        migrations.AddField(
            model_name='teams',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Stadiums'),
        ),
        migrations.AddField(
            model_name='members',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Nations'),
        ),
        migrations.AddField(
            model_name='members',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Positions'),
        ),
        migrations.AddField(
            model_name='members',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Users'),
        ),
        migrations.AddField(
            model_name='memberhistory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Members'),
        ),
        migrations.AddField(
            model_name='memberhistory',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Teams'),
        ),
        migrations.AddField(
            model_name='matchs',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='soccer.Teams'),
        ),
        migrations.AddField(
            model_name='matchs',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='soccer.Teams'),
        ),
        migrations.AddField(
            model_name='matchs',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Leagues'),
        ),
        migrations.AddField(
            model_name='matchs',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Members'),
        ),
        migrations.AddField(
            model_name='leagues',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Levels'),
        ),
        migrations.AddField(
            model_name='leagues',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Nations'),
        ),
    ]
