# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_auto_20181227_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
