# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_auto_20181231_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchs',
            name='result',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='scorer',
        ),
        migrations.AddField(
            model_name='matchs',
            name='ascore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchs',
            name='hscore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchs',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.Stadiums'),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
