# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0006_teams_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchs',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccer.Leagues'),
        ),
    ]
