# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-30 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0007_auto_20190129_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='mmr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
