# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-30 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0009_auto_20190130_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchs',
            name='away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='soccer.Teams'),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='soccer.Teams'),
        ),
    ]
