# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0011_auto_20190208_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='fifaid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
