# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0012_leagues_fifaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagues',
            name='fifaid',
        ),
        migrations.AddField(
            model_name='teams',
            name='fifaid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
