# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0014_freeboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeboard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
