# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-11 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0015_auto_20190402_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=200)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('win', models.IntegerField(blank=True, null=True)),
                ('draw', models.IntegerField(blank=True, null=True)),
                ('defeat', models.IntegerField(blank=True, null=True)),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('loss', models.IntegerField(blank=True, null=True)),
                ('assist', models.IntegerField(blank=True, null=True)),
                ('foul', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teams',
            name='ranking',
        ),
        migrations.AddField(
            model_name='seasons',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Teams'),
        ),
    ]
